name: Matrix Workflow

on:
  push:
  workflow_dispatch:

jobs:
  deploy-os:
    strategy:
      fail-fast: true # false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest] # Can add windows and mac
        images: [hello-world, alpine]
        exclude: 
          - os: [windows-latest]
            images: [hello-world, alpine, nginx]
        include:
          - images: [nginx]
            os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Docker Info
        run: docker info
      - name: Docker Hello World
        run: docker pull ${{ matrix.images }}
      - name: List Images
        run: docker image ls

