name: Variables & Secrets
on: 
  push:
    branches:
      - main
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: sihasaneshubham
          DOCKER_IMAGE: actions-nginx
        run:
          echo docker build -t ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
      - name: Docker Login
        env:
          USERNAME: sihasaneshubham
          PASSWORD: Rashmi@2026
        run:
          echo docker login --username=$USERNAME --password=$PASSWORD
      - name: Docker Push
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: sihasaneshubham
          DOCKER_IMAGE: actions-nginx
        run: 
          echo docker push ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: sihasaneshubham
          DOCKER_IMAGE: actions-nginx
        run:
          echo docker run -d -p 80:80 ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
