# ENVIRONMENT VARIABLES & SECRETS AT STEPS LEVEL
# name: Variables & Secrets

# on: 
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   Docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         env:
#           DOCKER_REGISTRY: docker.io
#           DOCKER_USERNAME: sihasaneshubham
#           DOCKER_IMAGE: actions-nginx
#         run:
#           echo docker build -t ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
#       - name: Docker Login
#         env:
#           USERNAME: sihasaneshubham
#           PASSWORD: ******
#         run:
#           echo docker login --username=$USERNAME --password=$PASSWORD
#       - name: Docker Push
#         env:
#           DOCKER_REGISTRY: docker.io
#           DOCKER_USERNAME: sihasaneshubham
#           DOCKER_IMAGE: actions-nginx
#         run: 
#           echo docker push ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
#   Deploy:
#     needs: [Docker]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Run
#         env:
#           DOCKER_REGISTRY: docker.io
#           DOCKER_USERNAME: sihasaneshubham
#           DOCKER_IMAGE: actions-nginx
#         run:
#           echo docker run -d -p 80:80 ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest


# ENVIRONMENT VARIABLES & SECRETS AT STEPS LEVEL
# name: Variables & Secrets
# on: workflow_dispatch
# jobs:
#   Docker:
#     env:
#       DOCKER_REGISTRY: docker.io
#       DOCKER_USERNAME: sihasaneshubham
#       DOCKER_IMAGE: actions-nginx
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         run: echo docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:latest
#       - name: Docker Login
#         env:
#           DOCKER_PASSWORD: ******
#         run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
#       - name: Docker Push
#         run: echo docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:latest
        
#   Deploy:
#     env:
#       DOCKER_REGISTRY: docker.io
#       DOCKER_USERNAME: sihasaneshubham
#       DOCKER_IMAGE: actions-nginx
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Run
#         run: echo docker run -d -p 80:80 $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

# ENVIRONMENT 
name: Variables & Secrets
on: workflow_dispatch
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: sihasaneshubham
  DOCKER_IMAGE: actions-nginx
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
      - name: Docker Login
        env:
          DOCKER_PASSWORD: Rashmi@2026
        run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      - name: Docker Push
        run: echo docker push ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
        
  Deploy:
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: sihasaneshubham
      DOCKER_IMAGE: actions-nginx
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 80:80 ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest